name: CSS Quality

on:
  pull_request:
    branches: [master]

jobs:
  cssDiff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: CSS Analytics Diff
        uses: bartveneman/gh-action-css-diff@v0.1
        with:
          project-wallace-token: ${{ secrets.PROJECT_WALLACE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          css-path: ./style.css
